	package ServiceMod;
	
	import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.util.ArrayList;

import view.modeling.ViewableComponent;
import GenCol.Pair;
import GenService.ApplicationComposition;
import GenService.ServiceBroker;
import GenService.ServiceClient;
import GenService.ServiceLookupMessage;
import GenService.ServiceRouter;
	
	public class Primitive_S1_P1 extends ApplicationComposition{
		
		public final static double observation = 70;
		public ServiceBroker Broker;
		public ServiceRouter Router;
		
		public Primitive_S1_P1(){
			super("Voice Communication Service");
		}
		
		public void BrokerRouterConstruct(){
			
			//attributes 
			double available = 60;     //available time for broker
			double startTime = 0.5; 
		 	double bandwidth = 10;      //bandwidth for the network or router
            
		 	//Ceate an unique component
			Broker = new ServiceBroker("Broker", available, startTime);
			Router = new ServiceRouter("Router Link", bandwidth);			
			Broker.setBackgroundColor(Color.YELLOW);
			Router.setBackgroundColor(Color.PINK);
			
			BrokerList.add(Broker);
			RouterList.add(Router);			
		}
		
		public void PublisherConstruct(){
			
			ArrayList <Pair> Endpoints = new ArrayList <Pair> ();
	 		
			Endpoints.add(new Pair("qRate", "Double"));		
			VoiceComm Service1 = 
				new VoiceComm("VoiceComm", "Voice Communication", "Atomic", Endpoints, 1);
			Service1.setBackgroundColor(Color.CYAN);
			PublisherList.add(Service1);	
		}
		
		public void SubscriberConstruct(){
			
			//Construct ServiceLookup information: The list of service to subscribe
			ArrayList <ServiceLookupMessage> lookupList = new ArrayList <ServiceLookupMessage> ();
			lookupList.add(new ServiceLookupMessage("VoiceComm", "qRate", new Pair("Hz", 220500), 60));
			
			//Construct Subscriber with the list of service lookup message
			ServiceClient Subscriber1 = new ServiceClient("Subscriber1", lookupList, 0.1);			
			Subscriber1.setBackgroundColor(Color.GREEN);
			//Add the subscriber into the list
			SubscriberList.add(Subscriber1);
				
		}  
		
		public void TransducerConstruct(){
			BrokerTransd BroTrans  =  new BrokerTransd("BrokerTransd", observation);
			RouterTransd NecTrans  =  new RouterTransd("RouterTransd", observation);
			SubscriberTransd SubTrans1 =  new SubscriberTransd("Sub1Transd", observation);
			PublisherTransd PubTrans1 =  new PublisherTransd("VoiceCommTransd", observation);
			
			//Always the same order: Broker >> Network >> Subscriber >> Publisher
			TransducerList.add(BroTrans);
			TransducerList.add(NecTrans);
			TransducerList.add(SubTrans1);			
			TransducerList.add(PubTrans1);
		
		}   
   
   
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(976, 640);
        ((ViewableComponent)withName("VoiceCommTransd")).setPreferredLocation(new Point(466, 177));
        ((ViewableComponent)withName("Subscriber1")).setPreferredLocation(new Point(-7, 248));
        ((ViewableComponent)withName("Sub1Transd")).setPreferredLocation(new Point(14, 182));
        ((ViewableComponent)withName("Broker")).setPreferredLocation(new Point(166, 120));
        ((ViewableComponent)withName("RouterTransd")).setPreferredLocation(new Point(217, 207));
        ((ViewableComponent)withName("VoiceComm")).setPreferredLocation(new Point(453, 236));
        ((ViewableComponent)withName("BrokerTransd")).setPreferredLocation(new Point(179, 54));
        ((ViewableComponent)withName("Router Link")).setPreferredLocation(new Point(220, 272));
    }
}
