	package ServiceMod;
	
	import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.util.ArrayList;

import view.modeling.ViewableComponent;
import GenCol.Pair;
import GenService.CompositeService;
	
	public class ResortByZipServices extends CompositeService{
		
		public final static double observation = 70;
		
		
		public ResortByZipServices(){
			super("Resort By Zip Service");
		}	
		
		public void EndpointsConstruct(){
			
			Endpoints.add(new Pair("ResortByZip", "Double"));
			
		}
		
		public void PublisherConstruct(){			
			
			ArrayList <Pair> Endpoints = new ArrayList <Pair> ();	 		
			Endpoints.add(new Pair("CityByZip", "Double"));		
			USZipService Service1 = 
				new USZipService("USZip", "City by Zip Service", "Atomic", Endpoints, 1);
			Service1.setBackgroundColor(Color.CYAN);
			//Construct the publisher list
			PublisherList.add(Service1);
			
			Endpoints = new ArrayList <Pair> ();	 		
			Endpoints.add(new Pair("ResortByCity", "String"));		
			ResortService Service2 = 
				new ResortService("Resort", "Resort by City Service", "Atomic", Endpoints, 1);
			Service2.setBackgroundColor(Color.CYAN);
			PublisherList.add(Service2);
				
		}
		
		
		public void TransducerConstruct(){
			RouterTransd routerTrans  =  new RouterTransd("RouterTransd", observation);
			PublisherTransd PubTrans1 =  new PublisherTransd("USZipTransd", observation);
			PublisherTransd PubTrans2 =  new PublisherTransd("ResortTransd", observation);
			//Add a transducer for each publisher
			
			TransducerList.add(routerTrans);
			TransducerList.add(PubTrans1);
			TransducerList.add(PubTrans2);
		}
		
		public void CompositeConstruction(){
			FedexRateByZipService Service2 = new FedexRateByZipService();
			CoupledPublishersList.add(Service2);
			
		}
   
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(793, 542);
        ((ViewableComponent)withName("Router")).setPreferredLocation(new Point(361, 36));
        ((ViewableComponent)withName("USZip")).setPreferredLocation(new Point(0, 38));
        ((ViewableComponent)withName("Fedex Rate By Zip")).setPreferredLocation(new Point(7, 191));
        ((ViewableComponent)withName("USZipTransd")).setPreferredLocation(new Point(12, 112));
        ((ViewableComponent)withName("Resort")).setPreferredLocation(new Point(148, 106));
        ((ViewableComponent)withName("RouterTransd")).setPreferredLocation(new Point(226, 47));
        ((ViewableComponent)withName("ResortTransd")).setPreferredLocation(new Point(372, 126));
    }
}
