package swarmNet;

/**
 * <p>Title: swarmNet</p>
 * <p>Description: The swarm network based on DEVS formalism</p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: Arizona State University</p>
 * @author Ahmet Zengin
 * @version 1.0
 */
import java.awt.Dimension;
import java.awt.Point;

import swarmNet.Trace.EF;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import GenCol.doubleEnt;

public class Net5EF extends ViewableDigraph {
	
	public Net5EF() {
		super("SAMPLE OSPF NETWORK 1");
		ViewableDigraph swnt = new Net5("Network", 0.001, 0.001);
		ViewableDigraph expf = new EF("Experimental Frame", 0.1, 10);

		addInport("start");
		addInport("stop");

		add(expf);
		add(swnt);

		addTestInput("start", new doubleEnt(10));
		addTestInput("start", new doubleEnt(5));
		addTestInput("start", new doubleEnt(1));
		addTestInput("start", new doubleEnt(0.001));

		addCoupling(this, "start", expf, "start");
		addCoupling(this, "stop", expf, "stop");

		addCoupling(expf, "outEvent", swnt, "inEvent");
		addCoupling(swnt, "outEvent", expf, "inEvent");

		initialize();

		preferredSize = new Dimension(973, 555);
		expf.setPreferredLocation(new Point(304, 312));
		swnt.setPreferredLocation(new Point(25, 15));
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1203, 630);
        ((ViewableComponent)withName("Experimental Frame")).setPreferredLocation(new Point(436, 402));
        ((ViewableComponent)withName("Network")).setPreferredLocation(new Point(3, 24));
    }
}
