package swarmNet;

/**
 * <p>Title: swarmNet</p>
 * <p>Description: The swarm network based on DEVS formalism</p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: Arizona State University</p>
 * @author Ahmet Zengin
 * @version 1.0
 */
import java.awt.Dimension;
import java.awt.Point;

import swarmNet.Trace.EF;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import GenCol.doubleEnt;

public class Net50EF extends ViewableDigraph {
	
	public Net50EF() {
		super("SAMPLE OSPF NETWORK w/50");
		ViewableDigraph expf = new EF("Experimental Frame", 0.1, 10);
		ViewableDigraph swnt = new Network("Network/w50nodes", 1, 1,50);

		addInport("start");
		addInport("stop");

		add(expf);
		add(swnt);

		addTestInput("start", new doubleEnt(10));
		addTestInput("start", new doubleEnt(5));
		addTestInput("start", new doubleEnt(1));
		addTestInput("start", new doubleEnt(0.001));

		addCoupling(this, "start", expf, "start");
		addCoupling(this, "stop", expf, "stop");

		addCoupling(expf, "outEvent", swnt, "inEvent");
		addCoupling(swnt, "outEvent", expf, "inEvent");

		initialize();
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1294, 646);
        ((ViewableComponent)withName("Experimental Frame")).setPreferredLocation(new Point(428, 512));
        ((ViewableComponent)withName("Network")).setPreferredLocation(new Point(10, 18));
    }
}
