package ospff;



import java.awt.Dimension;
import java.awt.Point;

import model.modeling.IOBasicDevs;
import model.modeling.IODevs;
import model.modeling.componentIterator;




import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class networ extends ViewableDigraph {
	 private  RouterAtomicMode r[];
	 protected IODevs d;
	 protected componentIterator ci;
  public networ(){
    this("networ", 1,1);
  }

  public networ(String name, int iþleme_zamaný,int ip){
    super(name);
    make(iþleme_zamaný,ip);
    componentIterator c = getComponents().cIterator();
    int i=0;
   while(c.hasNext()) {
      IOBasicDevs iob=c.nextComponent();
      //System.out.println(iob.getName());
      if (iob.getName().substring(0,1).equals("R")){
        //System.out.println("this runs!!!"+iob.getName().substring(0,1));
        i++;
        paketformat  n = new paketformat("packet"+i);
        n.setHedef(new IPAddress(0,0,0,3));
        addTestInput("eternet_girisi0", n);
      }
    }
 }

protected void make(int iþleme_zamaný,int ip){
	
	r = new RouterAtomicMode[9];
	addInport("inEvent");
	addOutport("outEvent");
	addInport("eternet_giriþi0");
	addInport("eternet_giriþi1");
	addOutport("eternet_çýkýþý0");
	addOutport("eternet_çýkýþý1");
	
	int a=(ip++)*256;
	
	for(int i=0;i<8;i++){
	
	if (i % 7 == 0 || i % 7 == 2 || i % 7 == 3 || i % 7 ==6)r[i] = new RouterAtomicMode("Router"+i,  new IPAddress(a+i), iþleme_zamaný,2);
	else if (i % 7 == 1 || i % 7 == 4 || i % 7 == 5)r[i] = new RouterAtomicMode("Router"+i,  new IPAddress(a+i), iþleme_zamaný,3);
    else if ( i % 7 == 7 )r[i] = new RouterAtomicMode("Router"+i,  new IPAddress(a+i), iþleme_zamaný,1);
    add(r[i]);
	}
	   ci = getComponents().cIterator();

	    for (int i = 0; i < getComponents().size(); i++) {
	      d = ci.nextComponent();
	      if (d.getName().substring(0,4).equals("link")) continue;
	      addCoupling(d, "outEvent",this, "outEvent");
	      addCoupling(this, "inEvent", d, "inEvent");

	    }

	addCoupling(this, "eternet_giriþi0", r[0], "eternet_giriþi1");
	addCoupling(r[0], "eternet_çýkýþý1",this, "eternet_çýkýþý0" );
	addCoupling(this, "eternet_giriþi1",r[6], "eternet_giriþi1");
	addCoupling( r[6], "eternet_çýkýþý1",this, "eternet_çýkýþý1");
    addCoupling(r[0], "eternet_çýkýþý0", r[1], "eternet_giriþi0");
    addCoupling(r[1], "eternet_çýkýþý0",r[0], "eternet_giriþi0");
    addCoupling(r[1], "eternet_çýkýþý1", r[2], "eternet_giriþi0");
    addCoupling(r[2], "eternet_çýkýþý0",r[1], "eternet_giriþi1");
    addCoupling(r[1], "eternet_çýkýþý2", r[3], "eternet_giriþi0");
    addCoupling(r[3], "eternet_çýkýþý0",r[1], "eternet_giriþi2");
    addCoupling(r[2], "eternet_çýkýþý1", r[4], "eternet_giriþi0");
    addCoupling(r[4], "eternet_çýkýþý0",r[2], "eternet_giriþi1");
    addCoupling(r[3], "eternet_çýkýþý1", r[4], "eternet_giriþi1");
    addCoupling(r[4], "eternet_çýkýþý1",r[3], "eternet_giriþi1");
    addCoupling(r[4], "eternet_çýkýþý2",r[5], "eternet_giriþi0");
    addCoupling(r[5], "eternet_çýkýþý0",r[4], "eternet_giriþi2");
    addCoupling(r[5], "eternet_çýkýþý1",r[6], "eternet_giriþi0");
    addCoupling(r[6], "eternet_çýkýþý0",r[5], "eternet_giriþi1");
    addCoupling(r[5], "eternet_çýkýþý2",r[7], "eternet_giriþi0");
    addCoupling(r[7], "eternet_çýkýþý0",r[5], "eternet_giriþi2");
  

    initialize();

  }
 
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(623, 292);
        ((ViewableComponent)withName("Router2")).setPreferredLocation(new Point(50, 214));
        ((ViewableComponent)withName("Router6")).setPreferredLocation(new Point(58, 45));
        ((ViewableComponent)withName("Router3")).setPreferredLocation(new Point(52, 103));
        ((ViewableComponent)withName("Router0")).setPreferredLocation(new Point(-26, -14));
        ((ViewableComponent)withName("Router7")).setPreferredLocation(new Point(-65, 191));
        ((ViewableComponent)withName("Router5")).setPreferredLocation(new Point(53, 156));
        ((ViewableComponent)withName("Router4")).setPreferredLocation(new Point(-57, 38));
        ((ViewableComponent)withName("Router1")).setPreferredLocation(new Point(-20, 123));
    }
}
